### PR TITLE
Removing unused GitHub workflows

### PR DESCRIPTION
**Pull request by lizfaubell**
## Summary:
From labeling huddle today, removing the workflows we won't need in this repository. There are still several others that are disabled, but could be useful with some modification (such as CI/CD pipeline). I'll update those in a separate PR.

Issue: https://khanacademy.atlassian.net/browse/DI-529

## Test plan:
- let's see what happens when I submit this pr

### CODE REVIEW

**Review by wwells — APPROVED** [review]
LGTM.   Fine to test this removal, but I really don't have a good understanding of any implications if we wanted to a) pull latest from upstream fork or b) prep for a contribution back to label studio.

**Review by dat-boris — APPROVED** [review]
Thanks for the cleanup!

Looking at PR #3 's workflow
https://github.com/Khan/label-studio-frontend/actions/runs/5826766164

Looks like E2E test failed, I need to debug what's going on there to make sure it is not real failure, but otherwise we should remove those also.

**Comment by lizfaubell** [comment]
> Thanks for the cleanup!
> 
> Looking at PR #3 's workflow https://github.com/Khan/label-studio-frontend/actions/runs/5826766164
> 
> Looks like E2E test failed, I need to debug what's going on there to make sure it is not real failure, but otherwise we should remove those also.

I'm putting up separate prs to fix up the workflows we probably want to keep, will include that one! Disabling for now.

**Comment by lizfaubell** [comment]
> LGTM. Fine to test this removal, but I really don't have a good understanding of any implications if we wanted to a) pull latest from upstream fork or b) prep for a contribution back to label studio.

I *believe* it wouldn't pull the workflows if they've been deleted in this branch (but we can find out). If we want to prep for a contribution, I think that opening a pr against the original repo will run the actions from that repository - so we could potentially run into issues if we don't catch things that fail until it hits the upstream repo. Maybe if we get to that point we can make sure to have extra time for dealing with that.

**Pull request merged**
