### PR TITLE
Fix annotation for RichTextTable component

### PR DESCRIPTION
**Pull request by dat-boris**
## Summary:
Previously although RichTextTable display properly, the annotation
didn't work.

This PR is a result of a bunch of learning on how the registry works,
and realize a bunch of small things that we did wrong and need to hook up
properly.  These will be documented in our documentation [1].

[1] https://khanacademy.atlassian.net/wiki/spaces/INFRA/pages/2373714068/Label+Studio+Frontend+guide#Note%3A-Adding-new-components-need-to-update-registry-and-Mobx-types

Issue: https://khanacademy.atlassian.net/browse/DI-533

## Test plan:
- `yarn start` and goes to https://localhost:3000, and try out the
  annotation.

label-demo

### CODE REVIEW

**Comment by dat-boris** [comment]
Huh - the E2E test failure is worth debugging (I will circle back tmr)

```
  1) Date Time
       Check DateTime holds state between annotations and saves result:
     TypeError: s.updateGlobalOffsets is not a function
      at /home/runner/work/label-studio-frontend/label-studio-frontend/e2e/plugins/errorsCollector.js:175:16
```

I have no idea what the cypress test failure is, looks like it is a dependency failure.

**Review by wwells — APPROVED** [review]
**praise**:  Thank you for the clear linked FE documentation.    Great anchor as we start building out more documentation over the coming sprints.    Especially key for our team of *not* FE engineers ;)

**Comment by wwells** [comment]
> PS:   I added a placeholder note to the one-pager that once this is deployed we should validate using this by updating existing workflows and making sure our import/export commands still work....

**Comment by dat-boris** [comment]
Woohoo, check pass!  Landing now.

image

**Pull request merged**
